/// <reference types="vitest/config" />
import { defineConfig, type Plugin } from 'vite';
import react from '@vitejs/plugin-react';
import { VitePWA } from 'vite-plugin-pwa';
import { fileURLToPath, URL } from 'node:url';
import { readFileSync } from 'node:fs';

const pkg = JSON.parse(readFileSync(new URL('./package.json', import.meta.url), 'utf8')) as { version: string };

// The app is served from https://unterkraehe.github.io/BandOrganizer/ (R-CODE-09).
const BASE = '/BandOrganizer/';

// The service worker tells the app which version it is (F3 §6.4, v0.19.4): right after a deploy the
// CDN serves old and new files for a few minutes, and an old service worker must not be offered as
// an update. The version is in the file name, so no cache can hand out a stale copy.
const SW_VERSION_FILE = `sw-version-${pkg.version}.js`;
const APP_SHELL = `index.html?v=${pkg.version}`;
const swVersion = (): Plugin => ({
  name: 'bandapp-sw-version',
  generateBundle() {
    this.emitFile({
      type: 'asset',
      fileName: SW_VERSION_FILE,
      source: `/* generated by vite.config.ts */
self.BANDAPP_VERSION = ${JSON.stringify(pkg.version)};
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'GET_VERSION' && event.ports[0]) event.ports[0].postMessage({ version: self.BANDAPP_VERSION });
});
`,
    });
  },
});

export default defineConfig({
  base: BASE,
  define: { __APP_VERSION__: JSON.stringify(pkg.version) },
  resolve: {
    alias: { '@': fileURLToPath(new URL('./src', import.meta.url)) },
  },
  plugins: [
    react(),
    swVersion(),
    VitePWA({
      registerType: 'prompt',
      includeAssets: ['icons/apple-touch-icon.png', 'icons/favicon.svg'],
      manifest: {
        // App name also lives in src/locales/de/common.json (R-I18N-07).
        name: 'Overload App',
        short_name: 'Overload App',
        description: 'Songs, Termine, Setlists und Chat für die Band',
        lang: 'de',
        start_url: BASE,
        scope: BASE,
        display: 'standalone',
        background_color: '#0E0E10',
        theme_color: '#0E0E10',
        icons: [
          { src: 'icons/icon-192.png', sizes: '192x192', type: 'image/png' },
          { src: 'icons/icon-512.png', sizes: '512x512', type: 'image/png' },
          { src: 'icons/icon-maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
        ],
      },
      workbox: {
        globPatterns: ['**/*.{js,css,html,svg,png,woff2}'],
        // The app shell is precached under a versioned address: the CDN has never seen it, so a new
        // service worker can't pick up a stale index.html of the previous version (v0.19.4).
        navigateFallback: APP_SHELL,
        manifestTransforms: [async (entries) => ({ manifest: entries.map((entry) => (entry.url === 'index.html' ? { ...entry, url: APP_SHELL } : entry)), warnings: [] })],
        // The OAuth callback must always come from the network.
        navigateFallbackDenylist: [/callback\.html/],
        // push notifications: handlers live in public/push-sw.js (F6 §4.5); version answer: see swVersion above
        importScripts: ['push-sw.js', SW_VERSION_FILE],
      },
    }),
  ],
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: ['./src/test/setup.ts'],
    alias: { 'virtual:pwa-register/react': fileURLToPath(new URL('./src/test/pwaRegisterMock.ts', import.meta.url)) },
    css: false,
  },
});
